BUZZER_PIN = 4

TBL_INVERT_DIRECTION = False
TBL_TID = 0
TBL_DIR_PIN = 11
TBL_STP_PIN = 12
TBL_STP_OFF_TIME_MICRO_SECONDS = 10
TBL_STP_COOLDOWN_MICRO_SECONDS = 10

ARM_PIN = 9  # NEEDS PWM
ARM_TID = 1
