import os

BUZZER_PIN = 4

TBL_INVERT_DIRECTION = False
TBL_TID = 0
TBL_DIR_PIN = 23
TBL_STP_PIN = 24
TBL_STP_OFF_TIME_MICRO_SECONDS = 500  # Microseconds
TBL_STP_COOLDOWN_MICRO_SECONDS = 500  # Microseconds

ARM_PIN = 13  # NEEDS PWM
ARM_TID = 1
ARM_TIME_PER_60_DEG = 0.17  # Seconds
ARM_TIME_PER_60_DEG_SAFETY = 0.1  # Seconds

DEV_NO_GPIO = os.getenv("STRINGBOT") != "TRUE"  # Disable GPIO usage for development
